//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIO.PowerShell.PIOWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PIOWebServiceReference.IPIOService")]
    public interface IPIOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanet", ReplyAction="http://tempuri.org/IPIOService/GetPlanetResponse")]
        PIO.Models.Planet GetPlanet(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanet", ReplyAction="http://tempuri.org/IPIOService/GetPlanetResponse")]
        System.Threading.Tasks.Task<PIO.Models.Planet> GetPlanetAsync(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanets", ReplyAction="http://tempuri.org/IPIOService/GetPlanetsResponse")]
        PIO.Models.Planet[] GetPlanets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanets", ReplyAction="http://tempuri.org/IPIOService/GetPlanetsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Planet[]> GetPlanetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactory", ReplyAction="http://tempuri.org/IPIOService/GetFactoryResponse")]
        PIO.Models.Factory GetFactory(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactory", ReplyAction="http://tempuri.org/IPIOService/GetFactoryResponse")]
        System.Threading.Tasks.Task<PIO.Models.Factory> GetFactoryAsync(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactories", ReplyAction="http://tempuri.org/IPIOService/GetFactoriesResponse")]
        PIO.Models.Factory[] GetFactories(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactories", ReplyAction="http://tempuri.org/IPIOService/GetFactoriesResponse")]
        System.Threading.Tasks.Task<PIO.Models.Factory[]> GetFactoriesAsync(int PlanetID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPIOServiceChannel : PIO.PowerShell.PIOWebServiceReference.IPIOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PIOServiceClient : System.ServiceModel.ClientBase<PIO.PowerShell.PIOWebServiceReference.IPIOService>, PIO.PowerShell.PIOWebServiceReference.IPIOService {
        
        public PIOServiceClient() {
        }
        
        public PIOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PIOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PIO.Models.Planet GetPlanet(int PlanetID) {
            return base.Channel.GetPlanet(PlanetID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Planet> GetPlanetAsync(int PlanetID) {
            return base.Channel.GetPlanetAsync(PlanetID);
        }
        
        public PIO.Models.Planet[] GetPlanets() {
            return base.Channel.GetPlanets();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Planet[]> GetPlanetsAsync() {
            return base.Channel.GetPlanetsAsync();
        }
        
        public PIO.Models.Factory GetFactory(int FactoryID) {
            return base.Channel.GetFactory(FactoryID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Factory> GetFactoryAsync(int FactoryID) {
            return base.Channel.GetFactoryAsync(FactoryID);
        }
        
        public PIO.Models.Factory[] GetFactories(int PlanetID) {
            return base.Channel.GetFactories(PlanetID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Factory[]> GetFactoriesAsync(int PlanetID) {
            return base.Channel.GetFactoriesAsync(PlanetID);
        }
    }
}
