//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIO.PowerShell.PIOWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PIOWebServiceReference.IPIOService")]
    public interface IPIOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanet", ReplyAction="http://tempuri.org/IPIOService/GetPlanetResponse")]
        PIO.Models.Planet GetPlanet(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanet", ReplyAction="http://tempuri.org/IPIOService/GetPlanetResponse")]
        System.Threading.Tasks.Task<PIO.Models.Planet> GetPlanetAsync(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanets", ReplyAction="http://tempuri.org/IPIOService/GetPlanetsResponse")]
        PIO.Models.Planet[] GetPlanets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanets", ReplyAction="http://tempuri.org/IPIOService/GetPlanetsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Planet[]> GetPlanetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactory", ReplyAction="http://tempuri.org/IPIOService/GetFactoryResponse")]
        PIO.Models.Factory GetFactory(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactory", ReplyAction="http://tempuri.org/IPIOService/GetFactoryResponse")]
        System.Threading.Tasks.Task<PIO.Models.Factory> GetFactoryAsync(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactories", ReplyAction="http://tempuri.org/IPIOService/GetFactoriesResponse")]
        PIO.Models.Factory[] GetFactories(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactories", ReplyAction="http://tempuri.org/IPIOService/GetFactoriesResponse")]
        System.Threading.Tasks.Task<PIO.Models.Factory[]> GetFactoriesAsync(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorker", ReplyAction="http://tempuri.org/IPIOService/GetWorkerResponse")]
        PIO.Models.Worker GetWorker(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorker", ReplyAction="http://tempuri.org/IPIOService/GetWorkerResponse")]
        System.Threading.Tasks.Task<PIO.Models.Worker> GetWorkerAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorkers", ReplyAction="http://tempuri.org/IPIOService/GetWorkersResponse")]
        PIO.Models.Worker[] GetWorkers(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorkers", ReplyAction="http://tempuri.org/IPIOService/GetWorkersResponse")]
        System.Threading.Tasks.Task<PIO.Models.Worker[]> GetWorkersAsync(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStack", ReplyAction="http://tempuri.org/IPIOService/GetStackResponse")]
        PIO.Models.Stack GetStack(int StackID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStack", ReplyAction="http://tempuri.org/IPIOService/GetStackResponse")]
        System.Threading.Tasks.Task<PIO.Models.Stack> GetStackAsync(int StackID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStacks", ReplyAction="http://tempuri.org/IPIOService/GetStacksResponse")]
        PIO.Models.Stack[] GetStacks(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStacks", ReplyAction="http://tempuri.org/IPIOService/GetStacksResponse")]
        System.Threading.Tasks.Task<PIO.Models.Stack[]> GetStacksAsync(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceType", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypeResponse")]
        PIO.Models.ResourceType GetResourceType(int ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceType", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypeResponse")]
        System.Threading.Tasks.Task<PIO.Models.ResourceType> GetResourceTypeAsync(int ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceTypes", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypesResponse")]
        PIO.Models.ResourceType[] GetResourceTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceTypes", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypesResponse")]
        System.Threading.Tasks.Task<PIO.Models.ResourceType[]> GetResourceTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactoryType", ReplyAction="http://tempuri.org/IPIOService/GetFactoryTypeResponse")]
        PIO.Models.FactoryType GetFactoryType(int FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactoryType", ReplyAction="http://tempuri.org/IPIOService/GetFactoryTypeResponse")]
        System.Threading.Tasks.Task<PIO.Models.FactoryType> GetFactoryTypeAsync(int FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactoryTypes", ReplyAction="http://tempuri.org/IPIOService/GetFactoryTypesResponse")]
        PIO.Models.FactoryType[] GetFactoryTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactoryTypes", ReplyAction="http://tempuri.org/IPIOService/GetFactoryTypesResponse")]
        System.Threading.Tasks.Task<PIO.Models.FactoryType[]> GetFactoryTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskType", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypeResponse")]
        PIO.Models.TaskType GetTaskType(int TaskTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskType", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypeResponse")]
        System.Threading.Tasks.Task<PIO.Models.TaskType> GetTaskTypeAsync(int TaskTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskTypes", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypesResponse")]
        PIO.Models.TaskType[] GetTaskTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskTypes", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypesResponse")]
        System.Threading.Tasks.Task<PIO.Models.TaskType[]> GetTaskTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterial", ReplyAction="http://tempuri.org/IPIOService/GetMaterialResponse")]
        PIO.Models.Material GetMaterial(int MaterialID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterial", ReplyAction="http://tempuri.org/IPIOService/GetMaterialResponse")]
        System.Threading.Tasks.Task<PIO.Models.Material> GetMaterialAsync(int MaterialID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterials", ReplyAction="http://tempuri.org/IPIOService/GetMaterialsResponse")]
        PIO.Models.Material[] GetMaterials(int FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterials", ReplyAction="http://tempuri.org/IPIOService/GetMaterialsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Material[]> GetMaterialsAsync(int FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredient", ReplyAction="http://tempuri.org/IPIOService/GetIngredientResponse")]
        PIO.Models.Ingredient GetIngredient(int IngredientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredient", ReplyAction="http://tempuri.org/IPIOService/GetIngredientResponse")]
        System.Threading.Tasks.Task<PIO.Models.Ingredient> GetIngredientAsync(int IngredientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredients", ReplyAction="http://tempuri.org/IPIOService/GetIngredientsResponse")]
        PIO.Models.Ingredient[] GetIngredients(int FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredients", ReplyAction="http://tempuri.org/IPIOService/GetIngredientsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Ingredient[]> GetIngredientsAsync(int FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProduct", ReplyAction="http://tempuri.org/IPIOService/GetProductResponse")]
        PIO.Models.Product GetProduct(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProduct", ReplyAction="http://tempuri.org/IPIOService/GetProductResponse")]
        System.Threading.Tasks.Task<PIO.Models.Product> GetProductAsync(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProducts", ReplyAction="http://tempuri.org/IPIOService/GetProductsResponse")]
        PIO.Models.Product[] GetProducts(int FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProducts", ReplyAction="http://tempuri.org/IPIOService/GetProductsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Product[]> GetProductsAsync(int FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTask", ReplyAction="http://tempuri.org/IPIOService/GetTaskResponse")]
        PIO.Models.Task GetTask(int TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTask", ReplyAction="http://tempuri.org/IPIOService/GetTaskResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> GetTaskAsync(int TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTasks", ReplyAction="http://tempuri.org/IPIOService/GetTasksResponse")]
        PIO.Models.Task[] GetTasks(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTasks", ReplyAction="http://tempuri.org/IPIOService/GetTasksResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task[]> GetTasksAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/HasEnoughResourcesToProduce", ReplyAction="http://tempuri.org/IPIOService/HasEnoughResourcesToProduceResponse")]
        bool HasEnoughResourcesToProduce(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/HasEnoughResourcesToProduce", ReplyAction="http://tempuri.org/IPIOService/HasEnoughResourcesToProduceResponse")]
        System.Threading.Tasks.Task<bool> HasEnoughResourcesToProduceAsync(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Produce", ReplyAction="http://tempuri.org/IPIOService/ProduceResponse")]
        PIO.Models.Task Produce(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Produce", ReplyAction="http://tempuri.org/IPIOService/ProduceResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> ProduceAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/MoveTo", ReplyAction="http://tempuri.org/IPIOService/MoveToResponse")]
        PIO.Models.Task MoveTo(int WorkerID, int TargetFactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/MoveTo", ReplyAction="http://tempuri.org/IPIOService/MoveToResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> MoveToAsync(int WorkerID, int TargetFactoryID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPIOServiceChannel : PIO.PowerShell.PIOWebServiceReference.IPIOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PIOServiceClient : System.ServiceModel.ClientBase<PIO.PowerShell.PIOWebServiceReference.IPIOService>, PIO.PowerShell.PIOWebServiceReference.IPIOService {
        
        public PIOServiceClient() {
        }
        
        public PIOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PIOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PIO.Models.Planet GetPlanet(int PlanetID) {
            return base.Channel.GetPlanet(PlanetID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Planet> GetPlanetAsync(int PlanetID) {
            return base.Channel.GetPlanetAsync(PlanetID);
        }
        
        public PIO.Models.Planet[] GetPlanets() {
            return base.Channel.GetPlanets();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Planet[]> GetPlanetsAsync() {
            return base.Channel.GetPlanetsAsync();
        }
        
        public PIO.Models.Factory GetFactory(int FactoryID) {
            return base.Channel.GetFactory(FactoryID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Factory> GetFactoryAsync(int FactoryID) {
            return base.Channel.GetFactoryAsync(FactoryID);
        }
        
        public PIO.Models.Factory[] GetFactories(int PlanetID) {
            return base.Channel.GetFactories(PlanetID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Factory[]> GetFactoriesAsync(int PlanetID) {
            return base.Channel.GetFactoriesAsync(PlanetID);
        }
        
        public PIO.Models.Worker GetWorker(int WorkerID) {
            return base.Channel.GetWorker(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Worker> GetWorkerAsync(int WorkerID) {
            return base.Channel.GetWorkerAsync(WorkerID);
        }
        
        public PIO.Models.Worker[] GetWorkers(int FactoryID) {
            return base.Channel.GetWorkers(FactoryID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Worker[]> GetWorkersAsync(int FactoryID) {
            return base.Channel.GetWorkersAsync(FactoryID);
        }
        
        public PIO.Models.Stack GetStack(int StackID) {
            return base.Channel.GetStack(StackID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Stack> GetStackAsync(int StackID) {
            return base.Channel.GetStackAsync(StackID);
        }
        
        public PIO.Models.Stack[] GetStacks(int FactoryID) {
            return base.Channel.GetStacks(FactoryID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Stack[]> GetStacksAsync(int FactoryID) {
            return base.Channel.GetStacksAsync(FactoryID);
        }
        
        public PIO.Models.ResourceType GetResourceType(int ResourceTypeID) {
            return base.Channel.GetResourceType(ResourceTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.ResourceType> GetResourceTypeAsync(int ResourceTypeID) {
            return base.Channel.GetResourceTypeAsync(ResourceTypeID);
        }
        
        public PIO.Models.ResourceType[] GetResourceTypes() {
            return base.Channel.GetResourceTypes();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.ResourceType[]> GetResourceTypesAsync() {
            return base.Channel.GetResourceTypesAsync();
        }
        
        public PIO.Models.FactoryType GetFactoryType(int FactoryTypeID) {
            return base.Channel.GetFactoryType(FactoryTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.FactoryType> GetFactoryTypeAsync(int FactoryTypeID) {
            return base.Channel.GetFactoryTypeAsync(FactoryTypeID);
        }
        
        public PIO.Models.FactoryType[] GetFactoryTypes() {
            return base.Channel.GetFactoryTypes();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.FactoryType[]> GetFactoryTypesAsync() {
            return base.Channel.GetFactoryTypesAsync();
        }
        
        public PIO.Models.TaskType GetTaskType(int TaskTypeID) {
            return base.Channel.GetTaskType(TaskTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.TaskType> GetTaskTypeAsync(int TaskTypeID) {
            return base.Channel.GetTaskTypeAsync(TaskTypeID);
        }
        
        public PIO.Models.TaskType[] GetTaskTypes() {
            return base.Channel.GetTaskTypes();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.TaskType[]> GetTaskTypesAsync() {
            return base.Channel.GetTaskTypesAsync();
        }
        
        public PIO.Models.Material GetMaterial(int MaterialID) {
            return base.Channel.GetMaterial(MaterialID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Material> GetMaterialAsync(int MaterialID) {
            return base.Channel.GetMaterialAsync(MaterialID);
        }
        
        public PIO.Models.Material[] GetMaterials(int FactoryTypeID) {
            return base.Channel.GetMaterials(FactoryTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Material[]> GetMaterialsAsync(int FactoryTypeID) {
            return base.Channel.GetMaterialsAsync(FactoryTypeID);
        }
        
        public PIO.Models.Ingredient GetIngredient(int IngredientID) {
            return base.Channel.GetIngredient(IngredientID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Ingredient> GetIngredientAsync(int IngredientID) {
            return base.Channel.GetIngredientAsync(IngredientID);
        }
        
        public PIO.Models.Ingredient[] GetIngredients(int FactoryTypeID) {
            return base.Channel.GetIngredients(FactoryTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Ingredient[]> GetIngredientsAsync(int FactoryTypeID) {
            return base.Channel.GetIngredientsAsync(FactoryTypeID);
        }
        
        public PIO.Models.Product GetProduct(int ProductID) {
            return base.Channel.GetProduct(ProductID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Product> GetProductAsync(int ProductID) {
            return base.Channel.GetProductAsync(ProductID);
        }
        
        public PIO.Models.Product[] GetProducts(int FactoryTypeID) {
            return base.Channel.GetProducts(FactoryTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Product[]> GetProductsAsync(int FactoryTypeID) {
            return base.Channel.GetProductsAsync(FactoryTypeID);
        }
        
        public PIO.Models.Task GetTask(int TaskID) {
            return base.Channel.GetTask(TaskID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> GetTaskAsync(int TaskID) {
            return base.Channel.GetTaskAsync(TaskID);
        }
        
        public PIO.Models.Task[] GetTasks(int WorkerID) {
            return base.Channel.GetTasks(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task[]> GetTasksAsync(int WorkerID) {
            return base.Channel.GetTasksAsync(WorkerID);
        }
        
        public bool HasEnoughResourcesToProduce(int FactoryID) {
            return base.Channel.HasEnoughResourcesToProduce(FactoryID);
        }
        
        public System.Threading.Tasks.Task<bool> HasEnoughResourcesToProduceAsync(int FactoryID) {
            return base.Channel.HasEnoughResourcesToProduceAsync(FactoryID);
        }
        
        public PIO.Models.Task Produce(int WorkerID) {
            return base.Channel.Produce(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> ProduceAsync(int WorkerID) {
            return base.Channel.ProduceAsync(WorkerID);
        }
        
        public PIO.Models.Task MoveTo(int WorkerID, int TargetFactoryID) {
            return base.Channel.MoveTo(WorkerID, TargetFactoryID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> MoveToAsync(int WorkerID, int TargetFactoryID) {
            return base.Channel.MoveToAsync(WorkerID, TargetFactoryID);
        }
    }
}
