//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIO.Bots.ClientLib.BotsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BotsServiceReference.IBotsService")]
    public interface IBotsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetOrder", ReplyAction="http://tempuri.org/IBotsService/GetOrderResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIO.Bots.Models.ProduceOrder))]
        PIO.Bots.Models.Order GetOrder(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetOrders", ReplyAction="http://tempuri.org/IBotsService/GetOrdersResponse")]
        PIO.Bots.Models.Order[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetProduceOrder", ReplyAction="http://tempuri.org/IBotsService/GetProduceOrderResponse")]
        PIO.Bots.Models.ProduceOrder GetProduceOrder(int ProduceOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetProduceOrders", ReplyAction="http://tempuri.org/IBotsService/GetProduceOrdersResponse")]
        PIO.Bots.Models.ProduceOrder[] GetProduceOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateProduceOrder", ReplyAction="http://tempuri.org/IBotsService/CreateProduceOrderResponse")]
        PIO.Bots.Models.ProduceOrder CreateProduceOrder(int PlanetID, int FactoryID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBotsServiceChannel : PIO.Bots.ClientLib.BotsServiceReference.IBotsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BotsServiceClient : System.ServiceModel.ClientBase<PIO.Bots.ClientLib.BotsServiceReference.IBotsService>, PIO.Bots.ClientLib.BotsServiceReference.IBotsService {
        
        public BotsServiceClient() {
        }
        
        public BotsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BotsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BotsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BotsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PIO.Bots.Models.Order GetOrder(int OrderID) {
            return base.Channel.GetOrder(OrderID);
        }
        
        public PIO.Bots.Models.Order[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public PIO.Bots.Models.ProduceOrder GetProduceOrder(int ProduceOrderID) {
            return base.Channel.GetProduceOrder(ProduceOrderID);
        }
        
        public PIO.Bots.Models.ProduceOrder[] GetProduceOrders() {
            return base.Channel.GetProduceOrders();
        }
        
        public PIO.Bots.Models.ProduceOrder CreateProduceOrder(int PlanetID, int FactoryID) {
            return base.Channel.CreateProduceOrder(PlanetID, FactoryID);
        }
    }
}
