//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIO.Bots.ClientLib.BotsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BotsServiceReference.IBotsService")]
    public interface IBotsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBot", ReplyAction="http://tempuri.org/IBotsService/GetBotResponse")]
        PIO.Bots.Models.Bot GetBot(int BotID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBot", ReplyAction="http://tempuri.org/IBotsService/GetBotResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.Bot> GetBotAsync(int BotID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBotForWorker", ReplyAction="http://tempuri.org/IBotsService/GetBotForWorkerResponse")]
        PIO.Bots.Models.Bot GetBotForWorker(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBotForWorker", ReplyAction="http://tempuri.org/IBotsService/GetBotForWorkerResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.Bot> GetBotForWorkerAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBots", ReplyAction="http://tempuri.org/IBotsService/GetBotsResponse")]
        PIO.Bots.Models.Bot[] GetBots();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBots", ReplyAction="http://tempuri.org/IBotsService/GetBotsResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.Bot[]> GetBotsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetOrder", ReplyAction="http://tempuri.org/IBotsService/GetOrderResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIO.Bots.Models.ProduceOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIO.Bots.Models.HarvestOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIO.Bots.Models.BuildOrder))]
        PIO.Bots.Models.Order GetOrder(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetOrder", ReplyAction="http://tempuri.org/IBotsService/GetOrderResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.Order> GetOrderAsync(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetOrders", ReplyAction="http://tempuri.org/IBotsService/GetOrdersResponse")]
        PIO.Bots.Models.Order[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetOrders", ReplyAction="http://tempuri.org/IBotsService/GetOrdersResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.Order[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetProduceOrder", ReplyAction="http://tempuri.org/IBotsService/GetProduceOrderResponse")]
        PIO.Bots.Models.ProduceOrder GetProduceOrder(int ProduceOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetProduceOrder", ReplyAction="http://tempuri.org/IBotsService/GetProduceOrderResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.ProduceOrder> GetProduceOrderAsync(int ProduceOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetProduceOrders", ReplyAction="http://tempuri.org/IBotsService/GetProduceOrdersResponse")]
        PIO.Bots.Models.ProduceOrder[] GetProduceOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetProduceOrders", ReplyAction="http://tempuri.org/IBotsService/GetProduceOrdersResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.ProduceOrder[]> GetProduceOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetProduceOrdersForBuilding", ReplyAction="http://tempuri.org/IBotsService/GetProduceOrdersForBuildingResponse")]
        PIO.Bots.Models.ProduceOrder[] GetProduceOrdersForBuilding(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetProduceOrdersForBuilding", ReplyAction="http://tempuri.org/IBotsService/GetProduceOrdersForBuildingResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.ProduceOrder[]> GetProduceOrdersForBuildingAsync(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetHarvestOrder", ReplyAction="http://tempuri.org/IBotsService/GetHarvestOrderResponse")]
        PIO.Bots.Models.HarvestOrder GetHarvestOrder(int HarvestOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetHarvestOrder", ReplyAction="http://tempuri.org/IBotsService/GetHarvestOrderResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.HarvestOrder> GetHarvestOrderAsync(int HarvestOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetHarvestOrders", ReplyAction="http://tempuri.org/IBotsService/GetHarvestOrdersResponse")]
        PIO.Bots.Models.HarvestOrder[] GetHarvestOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetHarvestOrders", ReplyAction="http://tempuri.org/IBotsService/GetHarvestOrdersResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.HarvestOrder[]> GetHarvestOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetHarvestOrdersForBuilding", ReplyAction="http://tempuri.org/IBotsService/GetHarvestOrdersForBuildingResponse")]
        PIO.Bots.Models.HarvestOrder[] GetHarvestOrdersForBuilding(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetHarvestOrdersForBuilding", ReplyAction="http://tempuri.org/IBotsService/GetHarvestOrdersForBuildingResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.HarvestOrder[]> GetHarvestOrdersForBuildingAsync(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBuildOrder", ReplyAction="http://tempuri.org/IBotsService/GetBuildOrderResponse")]
        PIO.Bots.Models.BuildOrder GetBuildOrder(int BuildOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBuildOrder", ReplyAction="http://tempuri.org/IBotsService/GetBuildOrderResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.BuildOrder> GetBuildOrderAsync(int BuildOrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBuildOrders", ReplyAction="http://tempuri.org/IBotsService/GetBuildOrdersResponse")]
        PIO.Bots.Models.BuildOrder[] GetBuildOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBuildOrders", ReplyAction="http://tempuri.org/IBotsService/GetBuildOrdersResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.BuildOrder[]> GetBuildOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBuildOrdersAtPosition", ReplyAction="http://tempuri.org/IBotsService/GetBuildOrdersAtPositionResponse")]
        PIO.Bots.Models.BuildOrder[] GetBuildOrdersAtPosition(int PlanetId, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/GetBuildOrdersAtPosition", ReplyAction="http://tempuri.org/IBotsService/GetBuildOrdersAtPositionResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.BuildOrder[]> GetBuildOrdersAtPositionAsync(int PlanetId, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateProduceOrder", ReplyAction="http://tempuri.org/IBotsService/CreateProduceOrderResponse")]
        PIO.Bots.Models.ProduceOrder CreateProduceOrder(int PlanetID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateProduceOrder", ReplyAction="http://tempuri.org/IBotsService/CreateProduceOrderResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.ProduceOrder> CreateProduceOrderAsync(int PlanetID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateHarvestOrder", ReplyAction="http://tempuri.org/IBotsService/CreateHarvestOrderResponse")]
        PIO.Bots.Models.HarvestOrder CreateHarvestOrder(int PlanetID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateHarvestOrder", ReplyAction="http://tempuri.org/IBotsService/CreateHarvestOrderResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.HarvestOrder> CreateHarvestOrderAsync(int PlanetID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateBuildOrder", ReplyAction="http://tempuri.org/IBotsService/CreateBuildOrderResponse")]
        PIO.Bots.Models.BuildOrder CreateBuildOrder(int PlanetID, PIO.Models.BuildingTypeIDs BuildingTypeID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateBuildOrder", ReplyAction="http://tempuri.org/IBotsService/CreateBuildOrderResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.BuildOrder> CreateBuildOrderAsync(int PlanetID, PIO.Models.BuildingTypeIDs BuildingTypeID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateBot", ReplyAction="http://tempuri.org/IBotsService/CreateBotResponse")]
        PIO.Bots.Models.Bot CreateBot(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/CreateBot", ReplyAction="http://tempuri.org/IBotsService/CreateBotResponse")]
        System.Threading.Tasks.Task<PIO.Bots.Models.Bot> CreateBotAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/DeleteBot", ReplyAction="http://tempuri.org/IBotsService/DeleteBotResponse")]
        void DeleteBot(int BotID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBotsService/DeleteBot", ReplyAction="http://tempuri.org/IBotsService/DeleteBotResponse")]
        System.Threading.Tasks.Task DeleteBotAsync(int BotID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBotsServiceChannel : PIO.Bots.ClientLib.BotsServiceReference.IBotsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BotsServiceClient : System.ServiceModel.ClientBase<PIO.Bots.ClientLib.BotsServiceReference.IBotsService>, PIO.Bots.ClientLib.BotsServiceReference.IBotsService {
        
        public BotsServiceClient() {
        }
        
        public BotsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BotsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BotsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BotsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PIO.Bots.Models.Bot GetBot(int BotID) {
            return base.Channel.GetBot(BotID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.Bot> GetBotAsync(int BotID) {
            return base.Channel.GetBotAsync(BotID);
        }
        
        public PIO.Bots.Models.Bot GetBotForWorker(int WorkerID) {
            return base.Channel.GetBotForWorker(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.Bot> GetBotForWorkerAsync(int WorkerID) {
            return base.Channel.GetBotForWorkerAsync(WorkerID);
        }
        
        public PIO.Bots.Models.Bot[] GetBots() {
            return base.Channel.GetBots();
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.Bot[]> GetBotsAsync() {
            return base.Channel.GetBotsAsync();
        }
        
        public PIO.Bots.Models.Order GetOrder(int OrderID) {
            return base.Channel.GetOrder(OrderID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.Order> GetOrderAsync(int OrderID) {
            return base.Channel.GetOrderAsync(OrderID);
        }
        
        public PIO.Bots.Models.Order[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.Order[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public PIO.Bots.Models.ProduceOrder GetProduceOrder(int ProduceOrderID) {
            return base.Channel.GetProduceOrder(ProduceOrderID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.ProduceOrder> GetProduceOrderAsync(int ProduceOrderID) {
            return base.Channel.GetProduceOrderAsync(ProduceOrderID);
        }
        
        public PIO.Bots.Models.ProduceOrder[] GetProduceOrders() {
            return base.Channel.GetProduceOrders();
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.ProduceOrder[]> GetProduceOrdersAsync() {
            return base.Channel.GetProduceOrdersAsync();
        }
        
        public PIO.Bots.Models.ProduceOrder[] GetProduceOrdersForBuilding(int BuildingID) {
            return base.Channel.GetProduceOrdersForBuilding(BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.ProduceOrder[]> GetProduceOrdersForBuildingAsync(int BuildingID) {
            return base.Channel.GetProduceOrdersForBuildingAsync(BuildingID);
        }
        
        public PIO.Bots.Models.HarvestOrder GetHarvestOrder(int HarvestOrderID) {
            return base.Channel.GetHarvestOrder(HarvestOrderID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.HarvestOrder> GetHarvestOrderAsync(int HarvestOrderID) {
            return base.Channel.GetHarvestOrderAsync(HarvestOrderID);
        }
        
        public PIO.Bots.Models.HarvestOrder[] GetHarvestOrders() {
            return base.Channel.GetHarvestOrders();
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.HarvestOrder[]> GetHarvestOrdersAsync() {
            return base.Channel.GetHarvestOrdersAsync();
        }
        
        public PIO.Bots.Models.HarvestOrder[] GetHarvestOrdersForBuilding(int BuildingID) {
            return base.Channel.GetHarvestOrdersForBuilding(BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.HarvestOrder[]> GetHarvestOrdersForBuildingAsync(int BuildingID) {
            return base.Channel.GetHarvestOrdersForBuildingAsync(BuildingID);
        }
        
        public PIO.Bots.Models.BuildOrder GetBuildOrder(int BuildOrderID) {
            return base.Channel.GetBuildOrder(BuildOrderID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.BuildOrder> GetBuildOrderAsync(int BuildOrderID) {
            return base.Channel.GetBuildOrderAsync(BuildOrderID);
        }
        
        public PIO.Bots.Models.BuildOrder[] GetBuildOrders() {
            return base.Channel.GetBuildOrders();
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.BuildOrder[]> GetBuildOrdersAsync() {
            return base.Channel.GetBuildOrdersAsync();
        }
        
        public PIO.Bots.Models.BuildOrder[] GetBuildOrdersAtPosition(int PlanetId, int X, int Y) {
            return base.Channel.GetBuildOrdersAtPosition(PlanetId, X, Y);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.BuildOrder[]> GetBuildOrdersAtPositionAsync(int PlanetId, int X, int Y) {
            return base.Channel.GetBuildOrdersAtPositionAsync(PlanetId, X, Y);
        }
        
        public PIO.Bots.Models.ProduceOrder CreateProduceOrder(int PlanetID, int BuildingID) {
            return base.Channel.CreateProduceOrder(PlanetID, BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.ProduceOrder> CreateProduceOrderAsync(int PlanetID, int BuildingID) {
            return base.Channel.CreateProduceOrderAsync(PlanetID, BuildingID);
        }
        
        public PIO.Bots.Models.HarvestOrder CreateHarvestOrder(int PlanetID, int BuildingID) {
            return base.Channel.CreateHarvestOrder(PlanetID, BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.HarvestOrder> CreateHarvestOrderAsync(int PlanetID, int BuildingID) {
            return base.Channel.CreateHarvestOrderAsync(PlanetID, BuildingID);
        }
        
        public PIO.Bots.Models.BuildOrder CreateBuildOrder(int PlanetID, PIO.Models.BuildingTypeIDs BuildingTypeID, int X, int Y) {
            return base.Channel.CreateBuildOrder(PlanetID, BuildingTypeID, X, Y);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.BuildOrder> CreateBuildOrderAsync(int PlanetID, PIO.Models.BuildingTypeIDs BuildingTypeID, int X, int Y) {
            return base.Channel.CreateBuildOrderAsync(PlanetID, BuildingTypeID, X, Y);
        }
        
        public PIO.Bots.Models.Bot CreateBot(int WorkerID) {
            return base.Channel.CreateBot(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Bots.Models.Bot> CreateBotAsync(int WorkerID) {
            return base.Channel.CreateBotAsync(WorkerID);
        }
        
        public void DeleteBot(int BotID) {
            base.Channel.DeleteBot(BotID);
        }
        
        public System.Threading.Tasks.Task DeleteBotAsync(int BotID) {
            return base.Channel.DeleteBotAsync(BotID);
        }
    }
}
