//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIO.ClientLib.PIOServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PIOServiceReference.IPIOService")]
    public interface IPIOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanet", ReplyAction="http://tempuri.org/IPIOService/GetPlanetResponse")]
        PIO.Models.Planet GetPlanet(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanet", ReplyAction="http://tempuri.org/IPIOService/GetPlanetResponse")]
        System.Threading.Tasks.Task<PIO.Models.Planet> GetPlanetAsync(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanets", ReplyAction="http://tempuri.org/IPIOService/GetPlanetsResponse")]
        PIO.Models.Planet[] GetPlanets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanets", ReplyAction="http://tempuri.org/IPIOService/GetPlanetsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Planet[]> GetPlanetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetCell", ReplyAction="http://tempuri.org/IPIOService/GetCellResponse")]
        PIO.Models.Cell GetCell(int CellID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetCell", ReplyAction="http://tempuri.org/IPIOService/GetCellResponse")]
        System.Threading.Tasks.Task<PIO.Models.Cell> GetCellAsync(int CellID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetCellAtPos", ReplyAction="http://tempuri.org/IPIOService/GetCellAtPosResponse")]
        PIO.Models.Cell GetCellAtPos(int PlanetID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetCellAtPos", ReplyAction="http://tempuri.org/IPIOService/GetCellAtPosResponse")]
        System.Threading.Tasks.Task<PIO.Models.Cell> GetCellAtPosAsync(int PlanetID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetCells", ReplyAction="http://tempuri.org/IPIOService/GetCellsResponse")]
        PIO.Models.Cell[] GetCells(int PlanetID, int X, int Y, int Width, int Height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetCells", ReplyAction="http://tempuri.org/IPIOService/GetCellsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Cell[]> GetCellsAsync(int PlanetID, int X, int Y, int Width, int Height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuilding", ReplyAction="http://tempuri.org/IPIOService/GetBuildingResponse")]
        PIO.Models.Building GetBuilding(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuilding", ReplyAction="http://tempuri.org/IPIOService/GetBuildingResponse")]
        System.Threading.Tasks.Task<PIO.Models.Building> GetBuildingAsync(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingAtPos", ReplyAction="http://tempuri.org/IPIOService/GetBuildingAtPosResponse")]
        PIO.Models.Building GetBuildingAtPos(int PlanetID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingAtPos", ReplyAction="http://tempuri.org/IPIOService/GetBuildingAtPosResponse")]
        System.Threading.Tasks.Task<PIO.Models.Building> GetBuildingAtPosAsync(int PlanetID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildings", ReplyAction="http://tempuri.org/IPIOService/GetBuildingsResponse")]
        PIO.Models.Building[] GetBuildings(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildings", ReplyAction="http://tempuri.org/IPIOService/GetBuildingsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Building[]> GetBuildingsAsync(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorker", ReplyAction="http://tempuri.org/IPIOService/GetWorkerResponse")]
        PIO.Models.Worker GetWorker(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorker", ReplyAction="http://tempuri.org/IPIOService/GetWorkerResponse")]
        System.Threading.Tasks.Task<PIO.Models.Worker> GetWorkerAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorkers", ReplyAction="http://tempuri.org/IPIOService/GetWorkersResponse")]
        PIO.Models.Worker[] GetWorkers(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorkers", ReplyAction="http://tempuri.org/IPIOService/GetWorkersResponse")]
        System.Threading.Tasks.Task<PIO.Models.Worker[]> GetWorkersAsync(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetAllWorkers", ReplyAction="http://tempuri.org/IPIOService/GetAllWorkersResponse")]
        PIO.Models.Worker[] GetAllWorkers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetAllWorkers", ReplyAction="http://tempuri.org/IPIOService/GetAllWorkersResponse")]
        System.Threading.Tasks.Task<PIO.Models.Worker[]> GetAllWorkersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStack", ReplyAction="http://tempuri.org/IPIOService/GetStackResponse")]
        PIO.Models.Stack GetStack(int StackID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStack", ReplyAction="http://tempuri.org/IPIOService/GetStackResponse")]
        System.Threading.Tasks.Task<PIO.Models.Stack> GetStackAsync(int StackID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/FindStack", ReplyAction="http://tempuri.org/IPIOService/FindStackResponse")]
        PIO.Models.Stack FindStack(int PlanetID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/FindStack", ReplyAction="http://tempuri.org/IPIOService/FindStackResponse")]
        System.Threading.Tasks.Task<PIO.Models.Stack> FindStackAsync(int PlanetID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStacks", ReplyAction="http://tempuri.org/IPIOService/GetStacksResponse")]
        PIO.Models.Stack[] GetStacks(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStacks", ReplyAction="http://tempuri.org/IPIOService/GetStacksResponse")]
        System.Threading.Tasks.Task<PIO.Models.Stack[]> GetStacksAsync(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStackQuantity", ReplyAction="http://tempuri.org/IPIOService/GetStackQuantityResponse")]
        int GetStackQuantity(int BuildingID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStackQuantity", ReplyAction="http://tempuri.org/IPIOService/GetStackQuantityResponse")]
        System.Threading.Tasks.Task<int> GetStackQuantityAsync(int BuildingID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceType", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypeResponse")]
        PIO.Models.ResourceType GetResourceType(PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceType", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypeResponse")]
        System.Threading.Tasks.Task<PIO.Models.ResourceType> GetResourceTypeAsync(PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceTypes", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypesResponse")]
        PIO.Models.ResourceType[] GetResourceTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceTypes", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypesResponse")]
        System.Threading.Tasks.Task<PIO.Models.ResourceType[]> GetResourceTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingType", ReplyAction="http://tempuri.org/IPIOService/GetBuildingTypeResponse")]
        PIO.Models.BuildingType GetBuildingType(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingType", ReplyAction="http://tempuri.org/IPIOService/GetBuildingTypeResponse")]
        System.Threading.Tasks.Task<PIO.Models.BuildingType> GetBuildingTypeAsync(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingTypes", ReplyAction="http://tempuri.org/IPIOService/GetBuildingTypesResponse")]
        PIO.Models.BuildingType[] GetBuildingTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingTypes", ReplyAction="http://tempuri.org/IPIOService/GetBuildingTypesResponse")]
        System.Threading.Tasks.Task<PIO.Models.BuildingType[]> GetBuildingTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskType", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypeResponse")]
        PIO.Models.TaskType GetTaskType(PIO.Models.TaskTypeIDs TaskTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskType", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypeResponse")]
        System.Threading.Tasks.Task<PIO.Models.TaskType> GetTaskTypeAsync(PIO.Models.TaskTypeIDs TaskTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskTypes", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypesResponse")]
        PIO.Models.TaskType[] GetTaskTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskTypes", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypesResponse")]
        System.Threading.Tasks.Task<PIO.Models.TaskType[]> GetTaskTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterial", ReplyAction="http://tempuri.org/IPIOService/GetMaterialResponse")]
        PIO.Models.Material GetMaterial(int MaterialID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterial", ReplyAction="http://tempuri.org/IPIOService/GetMaterialResponse")]
        System.Threading.Tasks.Task<PIO.Models.Material> GetMaterialAsync(int MaterialID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterials", ReplyAction="http://tempuri.org/IPIOService/GetMaterialsResponse")]
        PIO.Models.Material[] GetMaterials(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterials", ReplyAction="http://tempuri.org/IPIOService/GetMaterialsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Material[]> GetMaterialsAsync(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredient", ReplyAction="http://tempuri.org/IPIOService/GetIngredientResponse")]
        PIO.Models.Ingredient GetIngredient(int IngredientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredient", ReplyAction="http://tempuri.org/IPIOService/GetIngredientResponse")]
        System.Threading.Tasks.Task<PIO.Models.Ingredient> GetIngredientAsync(int IngredientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredients", ReplyAction="http://tempuri.org/IPIOService/GetIngredientsResponse")]
        PIO.Models.Ingredient[] GetIngredients(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredients", ReplyAction="http://tempuri.org/IPIOService/GetIngredientsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Ingredient[]> GetIngredientsAsync(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProduct", ReplyAction="http://tempuri.org/IPIOService/GetProductResponse")]
        PIO.Models.Product GetProduct(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProduct", ReplyAction="http://tempuri.org/IPIOService/GetProductResponse")]
        System.Threading.Tasks.Task<PIO.Models.Product> GetProductAsync(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProducts", ReplyAction="http://tempuri.org/IPIOService/GetProductsResponse")]
        PIO.Models.Product[] GetProducts(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProducts", ReplyAction="http://tempuri.org/IPIOService/GetProductsResponse")]
        System.Threading.Tasks.Task<PIO.Models.Product[]> GetProductsAsync(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTask", ReplyAction="http://tempuri.org/IPIOService/GetTaskResponse")]
        PIO.Models.Task GetTask(int TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTask", ReplyAction="http://tempuri.org/IPIOService/GetTaskResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> GetTaskAsync(int TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTasks", ReplyAction="http://tempuri.org/IPIOService/GetTasksResponse")]
        PIO.Models.Task[] GetTasks(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTasks", ReplyAction="http://tempuri.org/IPIOService/GetTasksResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task[]> GetTasksAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetLastTask", ReplyAction="http://tempuri.org/IPIOService/GetLastTaskResponse")]
        PIO.Models.Task GetLastTask(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetLastTask", ReplyAction="http://tempuri.org/IPIOService/GetLastTaskResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> GetLastTaskAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/HasEnoughResourcesToProduce", ReplyAction="http://tempuri.org/IPIOService/HasEnoughResourcesToProduceResponse")]
        bool HasEnoughResourcesToProduce(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/HasEnoughResourcesToProduce", ReplyAction="http://tempuri.org/IPIOService/HasEnoughResourcesToProduceResponse")]
        System.Threading.Tasks.Task<bool> HasEnoughResourcesToProduceAsync(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMissingResourcesToProduce", ReplyAction="http://tempuri.org/IPIOService/GetMissingResourcesToProduceResponse")]
        PIO.Models.ResourceTypeIDs[] GetMissingResourcesToProduce(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMissingResourcesToProduce", ReplyAction="http://tempuri.org/IPIOService/GetMissingResourcesToProduceResponse")]
        System.Threading.Tasks.Task<PIO.Models.ResourceTypeIDs[]> GetMissingResourcesToProduceAsync(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/HasEnoughResourcesToBuild", ReplyAction="http://tempuri.org/IPIOService/HasEnoughResourcesToBuildResponse")]
        bool HasEnoughResourcesToBuild(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/HasEnoughResourcesToBuild", ReplyAction="http://tempuri.org/IPIOService/HasEnoughResourcesToBuildResponse")]
        System.Threading.Tasks.Task<bool> HasEnoughResourcesToBuildAsync(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMissingResourcesToBuild", ReplyAction="http://tempuri.org/IPIOService/GetMissingResourcesToBuildResponse")]
        PIO.Models.ResourceTypeIDs[] GetMissingResourcesToBuild(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMissingResourcesToBuild", ReplyAction="http://tempuri.org/IPIOService/GetMissingResourcesToBuildResponse")]
        System.Threading.Tasks.Task<PIO.Models.ResourceTypeIDs[]> GetMissingResourcesToBuildAsync(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/WorkerIsInBuilding", ReplyAction="http://tempuri.org/IPIOService/WorkerIsInBuildingResponse")]
        bool WorkerIsInBuilding(int WorkerID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/WorkerIsInBuilding", ReplyAction="http://tempuri.org/IPIOService/WorkerIsInBuildingResponse")]
        System.Threading.Tasks.Task<bool> WorkerIsInBuildingAsync(int WorkerID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Idle", ReplyAction="http://tempuri.org/IPIOService/IdleResponse")]
        PIO.Models.Task Idle(int WorkerID, int Duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Idle", ReplyAction="http://tempuri.org/IPIOService/IdleResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> IdleAsync(int WorkerID, int Duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Produce", ReplyAction="http://tempuri.org/IPIOService/ProduceResponse")]
        PIO.Models.Task Produce(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Produce", ReplyAction="http://tempuri.org/IPIOService/ProduceResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> ProduceAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/MoveTo", ReplyAction="http://tempuri.org/IPIOService/MoveToResponse")]
        PIO.Models.Task MoveTo(int WorkerID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/MoveTo", ReplyAction="http://tempuri.org/IPIOService/MoveToResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> MoveToAsync(int WorkerID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/MoveToBuilding", ReplyAction="http://tempuri.org/IPIOService/MoveToBuildingResponse")]
        PIO.Models.Task MoveToBuilding(int WorkerID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/MoveToBuilding", ReplyAction="http://tempuri.org/IPIOService/MoveToBuildingResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> MoveToBuildingAsync(int WorkerID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Take", ReplyAction="http://tempuri.org/IPIOService/TakeResponse")]
        PIO.Models.Task Take(int WorkerID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Take", ReplyAction="http://tempuri.org/IPIOService/TakeResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> TakeAsync(int WorkerID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Store", ReplyAction="http://tempuri.org/IPIOService/StoreResponse")]
        PIO.Models.Task Store(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Store", ReplyAction="http://tempuri.org/IPIOService/StoreResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> StoreAsync(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/CreateBuilding", ReplyAction="http://tempuri.org/IPIOService/CreateBuildingResponse")]
        PIO.Models.Task CreateBuilding(int WorkerID, PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/CreateBuilding", ReplyAction="http://tempuri.org/IPIOService/CreateBuildingResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> CreateBuildingAsync(int WorkerID, PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Build", ReplyAction="http://tempuri.org/IPIOService/BuildResponse")]
        PIO.Models.Task Build(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Build", ReplyAction="http://tempuri.org/IPIOService/BuildResponse")]
        System.Threading.Tasks.Task<PIO.Models.Task> BuildAsync(int WorkerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPIOServiceChannel : PIO.ClientLib.PIOServiceReference.IPIOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PIOServiceClient : System.ServiceModel.ClientBase<PIO.ClientLib.PIOServiceReference.IPIOService>, PIO.ClientLib.PIOServiceReference.IPIOService {
        
        public PIOServiceClient() {
        }
        
        public PIOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PIOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PIO.Models.Planet GetPlanet(int PlanetID) {
            return base.Channel.GetPlanet(PlanetID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Planet> GetPlanetAsync(int PlanetID) {
            return base.Channel.GetPlanetAsync(PlanetID);
        }
        
        public PIO.Models.Planet[] GetPlanets() {
            return base.Channel.GetPlanets();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Planet[]> GetPlanetsAsync() {
            return base.Channel.GetPlanetsAsync();
        }
        
        public PIO.Models.Cell GetCell(int CellID) {
            return base.Channel.GetCell(CellID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Cell> GetCellAsync(int CellID) {
            return base.Channel.GetCellAsync(CellID);
        }
        
        public PIO.Models.Cell GetCellAtPos(int PlanetID, int X, int Y) {
            return base.Channel.GetCellAtPos(PlanetID, X, Y);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Cell> GetCellAtPosAsync(int PlanetID, int X, int Y) {
            return base.Channel.GetCellAtPosAsync(PlanetID, X, Y);
        }
        
        public PIO.Models.Cell[] GetCells(int PlanetID, int X, int Y, int Width, int Height) {
            return base.Channel.GetCells(PlanetID, X, Y, Width, Height);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Cell[]> GetCellsAsync(int PlanetID, int X, int Y, int Width, int Height) {
            return base.Channel.GetCellsAsync(PlanetID, X, Y, Width, Height);
        }
        
        public PIO.Models.Building GetBuilding(int BuildingID) {
            return base.Channel.GetBuilding(BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Building> GetBuildingAsync(int BuildingID) {
            return base.Channel.GetBuildingAsync(BuildingID);
        }
        
        public PIO.Models.Building GetBuildingAtPos(int PlanetID, int X, int Y) {
            return base.Channel.GetBuildingAtPos(PlanetID, X, Y);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Building> GetBuildingAtPosAsync(int PlanetID, int X, int Y) {
            return base.Channel.GetBuildingAtPosAsync(PlanetID, X, Y);
        }
        
        public PIO.Models.Building[] GetBuildings(int PlanetID) {
            return base.Channel.GetBuildings(PlanetID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Building[]> GetBuildingsAsync(int PlanetID) {
            return base.Channel.GetBuildingsAsync(PlanetID);
        }
        
        public PIO.Models.Worker GetWorker(int WorkerID) {
            return base.Channel.GetWorker(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Worker> GetWorkerAsync(int WorkerID) {
            return base.Channel.GetWorkerAsync(WorkerID);
        }
        
        public PIO.Models.Worker[] GetWorkers(int PlanetID) {
            return base.Channel.GetWorkers(PlanetID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Worker[]> GetWorkersAsync(int PlanetID) {
            return base.Channel.GetWorkersAsync(PlanetID);
        }
        
        public PIO.Models.Worker[] GetAllWorkers() {
            return base.Channel.GetAllWorkers();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Worker[]> GetAllWorkersAsync() {
            return base.Channel.GetAllWorkersAsync();
        }
        
        public PIO.Models.Stack GetStack(int StackID) {
            return base.Channel.GetStack(StackID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Stack> GetStackAsync(int StackID) {
            return base.Channel.GetStackAsync(StackID);
        }
        
        public PIO.Models.Stack FindStack(int PlanetID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.FindStack(PlanetID, ResourceTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Stack> FindStackAsync(int PlanetID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.FindStackAsync(PlanetID, ResourceTypeID);
        }
        
        public PIO.Models.Stack[] GetStacks(int BuildingID) {
            return base.Channel.GetStacks(BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Stack[]> GetStacksAsync(int BuildingID) {
            return base.Channel.GetStacksAsync(BuildingID);
        }
        
        public int GetStackQuantity(int BuildingID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.GetStackQuantity(BuildingID, ResourceTypeID);
        }
        
        public System.Threading.Tasks.Task<int> GetStackQuantityAsync(int BuildingID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.GetStackQuantityAsync(BuildingID, ResourceTypeID);
        }
        
        public PIO.Models.ResourceType GetResourceType(PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.GetResourceType(ResourceTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.ResourceType> GetResourceTypeAsync(PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.GetResourceTypeAsync(ResourceTypeID);
        }
        
        public PIO.Models.ResourceType[] GetResourceTypes() {
            return base.Channel.GetResourceTypes();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.ResourceType[]> GetResourceTypesAsync() {
            return base.Channel.GetResourceTypesAsync();
        }
        
        public PIO.Models.BuildingType GetBuildingType(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetBuildingType(BuildingTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.BuildingType> GetBuildingTypeAsync(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetBuildingTypeAsync(BuildingTypeID);
        }
        
        public PIO.Models.BuildingType[] GetBuildingTypes() {
            return base.Channel.GetBuildingTypes();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.BuildingType[]> GetBuildingTypesAsync() {
            return base.Channel.GetBuildingTypesAsync();
        }
        
        public PIO.Models.TaskType GetTaskType(PIO.Models.TaskTypeIDs TaskTypeID) {
            return base.Channel.GetTaskType(TaskTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.TaskType> GetTaskTypeAsync(PIO.Models.TaskTypeIDs TaskTypeID) {
            return base.Channel.GetTaskTypeAsync(TaskTypeID);
        }
        
        public PIO.Models.TaskType[] GetTaskTypes() {
            return base.Channel.GetTaskTypes();
        }
        
        public System.Threading.Tasks.Task<PIO.Models.TaskType[]> GetTaskTypesAsync() {
            return base.Channel.GetTaskTypesAsync();
        }
        
        public PIO.Models.Material GetMaterial(int MaterialID) {
            return base.Channel.GetMaterial(MaterialID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Material> GetMaterialAsync(int MaterialID) {
            return base.Channel.GetMaterialAsync(MaterialID);
        }
        
        public PIO.Models.Material[] GetMaterials(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetMaterials(BuildingTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Material[]> GetMaterialsAsync(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetMaterialsAsync(BuildingTypeID);
        }
        
        public PIO.Models.Ingredient GetIngredient(int IngredientID) {
            return base.Channel.GetIngredient(IngredientID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Ingredient> GetIngredientAsync(int IngredientID) {
            return base.Channel.GetIngredientAsync(IngredientID);
        }
        
        public PIO.Models.Ingredient[] GetIngredients(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetIngredients(BuildingTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Ingredient[]> GetIngredientsAsync(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetIngredientsAsync(BuildingTypeID);
        }
        
        public PIO.Models.Product GetProduct(int ProductID) {
            return base.Channel.GetProduct(ProductID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Product> GetProductAsync(int ProductID) {
            return base.Channel.GetProductAsync(ProductID);
        }
        
        public PIO.Models.Product[] GetProducts(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetProducts(BuildingTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Product[]> GetProductsAsync(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetProductsAsync(BuildingTypeID);
        }
        
        public PIO.Models.Task GetTask(int TaskID) {
            return base.Channel.GetTask(TaskID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> GetTaskAsync(int TaskID) {
            return base.Channel.GetTaskAsync(TaskID);
        }
        
        public PIO.Models.Task[] GetTasks(int WorkerID) {
            return base.Channel.GetTasks(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task[]> GetTasksAsync(int WorkerID) {
            return base.Channel.GetTasksAsync(WorkerID);
        }
        
        public PIO.Models.Task GetLastTask(int WorkerID) {
            return base.Channel.GetLastTask(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> GetLastTaskAsync(int WorkerID) {
            return base.Channel.GetLastTaskAsync(WorkerID);
        }
        
        public bool HasEnoughResourcesToProduce(int BuildingID) {
            return base.Channel.HasEnoughResourcesToProduce(BuildingID);
        }
        
        public System.Threading.Tasks.Task<bool> HasEnoughResourcesToProduceAsync(int BuildingID) {
            return base.Channel.HasEnoughResourcesToProduceAsync(BuildingID);
        }
        
        public PIO.Models.ResourceTypeIDs[] GetMissingResourcesToProduce(int BuildingID) {
            return base.Channel.GetMissingResourcesToProduce(BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.ResourceTypeIDs[]> GetMissingResourcesToProduceAsync(int BuildingID) {
            return base.Channel.GetMissingResourcesToProduceAsync(BuildingID);
        }
        
        public bool HasEnoughResourcesToBuild(int BuildingID) {
            return base.Channel.HasEnoughResourcesToBuild(BuildingID);
        }
        
        public System.Threading.Tasks.Task<bool> HasEnoughResourcesToBuildAsync(int BuildingID) {
            return base.Channel.HasEnoughResourcesToBuildAsync(BuildingID);
        }
        
        public PIO.Models.ResourceTypeIDs[] GetMissingResourcesToBuild(int BuildingID) {
            return base.Channel.GetMissingResourcesToBuild(BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.ResourceTypeIDs[]> GetMissingResourcesToBuildAsync(int BuildingID) {
            return base.Channel.GetMissingResourcesToBuildAsync(BuildingID);
        }
        
        public bool WorkerIsInBuilding(int WorkerID, int BuildingID) {
            return base.Channel.WorkerIsInBuilding(WorkerID, BuildingID);
        }
        
        public System.Threading.Tasks.Task<bool> WorkerIsInBuildingAsync(int WorkerID, int BuildingID) {
            return base.Channel.WorkerIsInBuildingAsync(WorkerID, BuildingID);
        }
        
        public PIO.Models.Task Idle(int WorkerID, int Duration) {
            return base.Channel.Idle(WorkerID, Duration);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> IdleAsync(int WorkerID, int Duration) {
            return base.Channel.IdleAsync(WorkerID, Duration);
        }
        
        public PIO.Models.Task Produce(int WorkerID) {
            return base.Channel.Produce(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> ProduceAsync(int WorkerID) {
            return base.Channel.ProduceAsync(WorkerID);
        }
        
        public PIO.Models.Task MoveTo(int WorkerID, int X, int Y) {
            return base.Channel.MoveTo(WorkerID, X, Y);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> MoveToAsync(int WorkerID, int X, int Y) {
            return base.Channel.MoveToAsync(WorkerID, X, Y);
        }
        
        public PIO.Models.Task MoveToBuilding(int WorkerID, int BuildingID) {
            return base.Channel.MoveToBuilding(WorkerID, BuildingID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> MoveToBuildingAsync(int WorkerID, int BuildingID) {
            return base.Channel.MoveToBuildingAsync(WorkerID, BuildingID);
        }
        
        public PIO.Models.Task Take(int WorkerID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.Take(WorkerID, ResourceTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> TakeAsync(int WorkerID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.TakeAsync(WorkerID, ResourceTypeID);
        }
        
        public PIO.Models.Task Store(int WorkerID) {
            return base.Channel.Store(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> StoreAsync(int WorkerID) {
            return base.Channel.StoreAsync(WorkerID);
        }
        
        public PIO.Models.Task CreateBuilding(int WorkerID, PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.CreateBuilding(WorkerID, BuildingTypeID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> CreateBuildingAsync(int WorkerID, PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.CreateBuildingAsync(WorkerID, BuildingTypeID);
        }
        
        public PIO.Models.Task Build(int WorkerID) {
            return base.Channel.Build(WorkerID);
        }
        
        public System.Threading.Tasks.Task<PIO.Models.Task> BuildAsync(int WorkerID) {
            return base.Channel.BuildAsync(WorkerID);
        }
    }
}
