//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIO.ClientLib.PIOServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PIOServiceReference.IPIOService")]
    public interface IPIOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanet", ReplyAction="http://tempuri.org/IPIOService/GetPlanetResponse")]
        PIO.Models.Planet GetPlanet(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetPlanets", ReplyAction="http://tempuri.org/IPIOService/GetPlanetsResponse")]
        PIO.Models.Planet[] GetPlanets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuilding", ReplyAction="http://tempuri.org/IPIOService/GetBuildingResponse")]
        PIO.Models.Building GetBuilding(int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingAtPos", ReplyAction="http://tempuri.org/IPIOService/GetBuildingAtPosResponse")]
        PIO.Models.Building GetBuildingAtPos(int PlanetID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildings", ReplyAction="http://tempuri.org/IPIOService/GetBuildingsResponse")]
        PIO.Models.Building[] GetBuildings(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactory", ReplyAction="http://tempuri.org/IPIOService/GetFactoryResponse")]
        PIO.Models.Factory GetFactory(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactoryAtPos", ReplyAction="http://tempuri.org/IPIOService/GetFactoryAtPosResponse")]
        PIO.Models.Factory GetFactoryAtPos(int PlanetID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactories", ReplyAction="http://tempuri.org/IPIOService/GetFactoriesResponse")]
        PIO.Models.Factory[] GetFactories(int PlanetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorker", ReplyAction="http://tempuri.org/IPIOService/GetWorkerResponse")]
        PIO.Models.Worker GetWorker(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetWorkers", ReplyAction="http://tempuri.org/IPIOService/GetWorkersResponse")]
        PIO.Models.Worker[] GetWorkers(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStack", ReplyAction="http://tempuri.org/IPIOService/GetStackResponse")]
        PIO.Models.Stack GetStack(int StackID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/FindStack", ReplyAction="http://tempuri.org/IPIOService/FindStackResponse")]
        PIO.Models.Stack FindStack(int PlanetID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStacks", ReplyAction="http://tempuri.org/IPIOService/GetStacksResponse")]
        PIO.Models.Stack[] GetStacks(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetStackQuantity", ReplyAction="http://tempuri.org/IPIOService/GetStackQuantityResponse")]
        int GetStackQuantity(int FactoryID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceType", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypeResponse")]
        PIO.Models.ResourceType GetResourceType(PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetResourceTypes", ReplyAction="http://tempuri.org/IPIOService/GetResourceTypesResponse")]
        PIO.Models.ResourceType[] GetResourceTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingType", ReplyAction="http://tempuri.org/IPIOService/GetBuildingTypeResponse")]
        PIO.Models.BuildingType GetBuildingType(PIO.Models.BuildingTypeIDs BuildingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetBuildingTypes", ReplyAction="http://tempuri.org/IPIOService/GetBuildingTypesResponse")]
        PIO.Models.BuildingType[] GetBuildingTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactoryType", ReplyAction="http://tempuri.org/IPIOService/GetFactoryTypeResponse")]
        PIO.Models.FactoryType GetFactoryType(PIO.Models.FactoryTypeIDs FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetFactoryTypes", ReplyAction="http://tempuri.org/IPIOService/GetFactoryTypesResponse")]
        PIO.Models.FactoryType[] GetFactoryTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskType", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypeResponse")]
        PIO.Models.TaskType GetTaskType(PIO.Models.TaskTypeIDs TaskTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTaskTypes", ReplyAction="http://tempuri.org/IPIOService/GetTaskTypesResponse")]
        PIO.Models.TaskType[] GetTaskTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterial", ReplyAction="http://tempuri.org/IPIOService/GetMaterialResponse")]
        PIO.Models.Material GetMaterial(int MaterialID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMaterials", ReplyAction="http://tempuri.org/IPIOService/GetMaterialsResponse")]
        PIO.Models.Material[] GetMaterials(PIO.Models.FactoryTypeIDs FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredient", ReplyAction="http://tempuri.org/IPIOService/GetIngredientResponse")]
        PIO.Models.Ingredient GetIngredient(int IngredientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetIngredients", ReplyAction="http://tempuri.org/IPIOService/GetIngredientsResponse")]
        PIO.Models.Ingredient[] GetIngredients(PIO.Models.FactoryTypeIDs FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProduct", ReplyAction="http://tempuri.org/IPIOService/GetProductResponse")]
        PIO.Models.Product GetProduct(int ProductID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetProducts", ReplyAction="http://tempuri.org/IPIOService/GetProductsResponse")]
        PIO.Models.Product[] GetProducts(PIO.Models.FactoryTypeIDs FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTask", ReplyAction="http://tempuri.org/IPIOService/GetTaskResponse")]
        PIO.Models.Task GetTask(int TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetTasks", ReplyAction="http://tempuri.org/IPIOService/GetTasksResponse")]
        PIO.Models.Task[] GetTasks(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetLastTask", ReplyAction="http://tempuri.org/IPIOService/GetLastTaskResponse")]
        PIO.Models.Task GetLastTask(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/HasEnoughResourcesToProduce", ReplyAction="http://tempuri.org/IPIOService/HasEnoughResourcesToProduceResponse")]
        bool HasEnoughResourcesToProduce(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/GetMissingResourcesToProduce", ReplyAction="http://tempuri.org/IPIOService/GetMissingResourcesToProduceResponse")]
        PIO.Models.ResourceTypeIDs[] GetMissingResourcesToProduce(int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/WorkerIsInFactory", ReplyAction="http://tempuri.org/IPIOService/WorkerIsInFactoryResponse")]
        bool WorkerIsInFactory(int WorkerID, int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/WorkerIsInBuilding", ReplyAction="http://tempuri.org/IPIOService/WorkerIsInBuildingResponse")]
        bool WorkerIsInBuilding(int WorkerID, int BuildingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Idle", ReplyAction="http://tempuri.org/IPIOService/IdleResponse")]
        PIO.Models.Task Idle(int WorkerID, int Duration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/Produce", ReplyAction="http://tempuri.org/IPIOService/ProduceResponse")]
        PIO.Models.Task Produce(int WorkerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/MoveTo", ReplyAction="http://tempuri.org/IPIOService/MoveToResponse")]
        PIO.Models.Task MoveTo(int WorkerID, int X, int Y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/MoveToFactory", ReplyAction="http://tempuri.org/IPIOService/MoveToFactoryResponse")]
        PIO.Models.Task MoveToFactory(int WorkerID, int FactoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/CarryTo", ReplyAction="http://tempuri.org/IPIOService/CarryToResponse")]
        PIO.Models.Task CarryTo(int WorkerID, int TargetFactoryID, PIO.Models.ResourceTypeIDs ResourceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/CreateBuilding", ReplyAction="http://tempuri.org/IPIOService/CreateBuildingResponse")]
        PIO.Models.Task CreateBuilding(int WorkerID, PIO.Models.FactoryTypeIDs FactoryTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPIOService/BuildFactory", ReplyAction="http://tempuri.org/IPIOService/BuildFactoryResponse")]
        PIO.Models.Task BuildFactory(int WorkerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPIOServiceChannel : PIO.ClientLib.PIOServiceReference.IPIOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PIOServiceClient : System.ServiceModel.ClientBase<PIO.ClientLib.PIOServiceReference.IPIOService>, PIO.ClientLib.PIOServiceReference.IPIOService {
        
        public PIOServiceClient() {
        }
        
        public PIOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PIOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PIOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PIO.Models.Planet GetPlanet(int PlanetID) {
            return base.Channel.GetPlanet(PlanetID);
        }
        
        public PIO.Models.Planet[] GetPlanets() {
            return base.Channel.GetPlanets();
        }
        
        public PIO.Models.Building GetBuilding(int BuildingID) {
            return base.Channel.GetBuilding(BuildingID);
        }
        
        public PIO.Models.Building GetBuildingAtPos(int PlanetID, int X, int Y) {
            return base.Channel.GetBuildingAtPos(PlanetID, X, Y);
        }
        
        public PIO.Models.Building[] GetBuildings(int PlanetID) {
            return base.Channel.GetBuildings(PlanetID);
        }
        
        public PIO.Models.Factory GetFactory(int FactoryID) {
            return base.Channel.GetFactory(FactoryID);
        }
        
        public PIO.Models.Factory GetFactoryAtPos(int PlanetID, int X, int Y) {
            return base.Channel.GetFactoryAtPos(PlanetID, X, Y);
        }
        
        public PIO.Models.Factory[] GetFactories(int PlanetID) {
            return base.Channel.GetFactories(PlanetID);
        }
        
        public PIO.Models.Worker GetWorker(int WorkerID) {
            return base.Channel.GetWorker(WorkerID);
        }
        
        public PIO.Models.Worker[] GetWorkers(int FactoryID) {
            return base.Channel.GetWorkers(FactoryID);
        }
        
        public PIO.Models.Stack GetStack(int StackID) {
            return base.Channel.GetStack(StackID);
        }
        
        public PIO.Models.Stack FindStack(int PlanetID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.FindStack(PlanetID, ResourceTypeID);
        }
        
        public PIO.Models.Stack[] GetStacks(int FactoryID) {
            return base.Channel.GetStacks(FactoryID);
        }
        
        public int GetStackQuantity(int FactoryID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.GetStackQuantity(FactoryID, ResourceTypeID);
        }
        
        public PIO.Models.ResourceType GetResourceType(PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.GetResourceType(ResourceTypeID);
        }
        
        public PIO.Models.ResourceType[] GetResourceTypes() {
            return base.Channel.GetResourceTypes();
        }
        
        public PIO.Models.BuildingType GetBuildingType(PIO.Models.BuildingTypeIDs BuildingTypeID) {
            return base.Channel.GetBuildingType(BuildingTypeID);
        }
        
        public PIO.Models.BuildingType[] GetBuildingTypes() {
            return base.Channel.GetBuildingTypes();
        }
        
        public PIO.Models.FactoryType GetFactoryType(PIO.Models.FactoryTypeIDs FactoryTypeID) {
            return base.Channel.GetFactoryType(FactoryTypeID);
        }
        
        public PIO.Models.FactoryType[] GetFactoryTypes() {
            return base.Channel.GetFactoryTypes();
        }
        
        public PIO.Models.TaskType GetTaskType(PIO.Models.TaskTypeIDs TaskTypeID) {
            return base.Channel.GetTaskType(TaskTypeID);
        }
        
        public PIO.Models.TaskType[] GetTaskTypes() {
            return base.Channel.GetTaskTypes();
        }
        
        public PIO.Models.Material GetMaterial(int MaterialID) {
            return base.Channel.GetMaterial(MaterialID);
        }
        
        public PIO.Models.Material[] GetMaterials(PIO.Models.FactoryTypeIDs FactoryTypeID) {
            return base.Channel.GetMaterials(FactoryTypeID);
        }
        
        public PIO.Models.Ingredient GetIngredient(int IngredientID) {
            return base.Channel.GetIngredient(IngredientID);
        }
        
        public PIO.Models.Ingredient[] GetIngredients(PIO.Models.FactoryTypeIDs FactoryTypeID) {
            return base.Channel.GetIngredients(FactoryTypeID);
        }
        
        public PIO.Models.Product GetProduct(int ProductID) {
            return base.Channel.GetProduct(ProductID);
        }
        
        public PIO.Models.Product[] GetProducts(PIO.Models.FactoryTypeIDs FactoryTypeID) {
            return base.Channel.GetProducts(FactoryTypeID);
        }
        
        public PIO.Models.Task GetTask(int TaskID) {
            return base.Channel.GetTask(TaskID);
        }
        
        public PIO.Models.Task[] GetTasks(int WorkerID) {
            return base.Channel.GetTasks(WorkerID);
        }
        
        public PIO.Models.Task GetLastTask(int WorkerID) {
            return base.Channel.GetLastTask(WorkerID);
        }
        
        public bool HasEnoughResourcesToProduce(int FactoryID) {
            return base.Channel.HasEnoughResourcesToProduce(FactoryID);
        }
        
        public PIO.Models.ResourceTypeIDs[] GetMissingResourcesToProduce(int FactoryID) {
            return base.Channel.GetMissingResourcesToProduce(FactoryID);
        }
        
        public bool WorkerIsInFactory(int WorkerID, int FactoryID) {
            return base.Channel.WorkerIsInFactory(WorkerID, FactoryID);
        }
        
        public bool WorkerIsInBuilding(int WorkerID, int BuildingID) {
            return base.Channel.WorkerIsInBuilding(WorkerID, BuildingID);
        }
        
        public PIO.Models.Task Idle(int WorkerID, int Duration) {
            return base.Channel.Idle(WorkerID, Duration);
        }
        
        public PIO.Models.Task Produce(int WorkerID) {
            return base.Channel.Produce(WorkerID);
        }
        
        public PIO.Models.Task MoveTo(int WorkerID, int X, int Y) {
            return base.Channel.MoveTo(WorkerID, X, Y);
        }
        
        public PIO.Models.Task MoveToFactory(int WorkerID, int FactoryID) {
            return base.Channel.MoveToFactory(WorkerID, FactoryID);
        }
        
        public PIO.Models.Task CarryTo(int WorkerID, int TargetFactoryID, PIO.Models.ResourceTypeIDs ResourceTypeID) {
            return base.Channel.CarryTo(WorkerID, TargetFactoryID, ResourceTypeID);
        }
        
        public PIO.Models.Task CreateBuilding(int WorkerID, PIO.Models.FactoryTypeIDs FactoryTypeID) {
            return base.Channel.CreateBuilding(WorkerID, FactoryTypeID);
        }
        
        public PIO.Models.Task BuildFactory(int WorkerID) {
            return base.Channel.BuildFactory(WorkerID);
        }
    }
}
